providers = ["php"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "bash ./scripts/start.sh"
