version: '3'
services:
  lean-startup-game:
    # user: "${UID}:${GID}"
    container_name: lean-startup-game
    hostname: lean-startup-game.local
    build: cnf/api
    tty: true
    volumes:
        - ../api:/app
        - ~/.ssh/id_rsa:/root/.ssh/id_rsa
        - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
        - ./cnf/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        - ./cnf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        - ./cnf/.inputrc:/root/.inputrc
        - ./cnf/git-prompt.sh:/root/git-prompt.sh
        - ./cnf/api/.bashrc:/root/.bashrc
        - ./cnf/api/apache.conf:/etc/apache2/sites-enabled/000-default.conf
        - ./.bash_history:/root/.bash_history
    ports:
      - 82:80
      - 5173:5173
    links:
      - mariadb:db
      - redis:redis
      - mailhog:mailhog

    environment:
      - NODE_ENV=development  # Set the Node.js environment if needed


  mariadb:
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    image: "mariadb:latest"
    volumes:
      - ./db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    links:
      - mariadb:db
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  redis:
    image: "redis:alpine"

